// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/12/24 17:08:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/wanti/code/InfoFlow/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wanti/code/InfoFlow/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wanti/code/InfoFlow/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wanti/code/InfoFlow/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wanti/code/InfoFlow/app/plugins/**/*.{js,ts,mjs}","/Users/wanti/code/InfoFlow/app/composables/**/*.{js,ts,mjs}","/Users/wanti/code/InfoFlow/app/utils/**/*.{js,ts,mjs}","/Users/wanti/code/InfoFlow/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/wanti/code/InfoFlow/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/wanti/code/InfoFlow/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/wanti/code/InfoFlow/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;